const data = {
  products:[
    {
      _id: '1',
      name: 'Kit manutenção / 5 pçs',
      category: 'Ferramentas',
      image: '/images/kit5pcas_manut.jpg',
      price: 120,
      brand: 'Ada',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Substrato Amazonia',
      category: 'Substratos',
      image: '/images/amazonia_substrato3.jpg',
      price: 350,
      brand: 'Ada',
      rating: 5,
      numReviews: 25,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Cilindro CO2 6kg',
      category: 'Cilindros',
      image: '/images/cilindroCo2.jpg',
      price: 500,
      brand: 'Ista',
      rating: 3.5,
      numReviews: 7,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Difusor Co2',
      category: 'Acessórios',
      image: '/images/difusor2.jpg',
      price: 15,
      brand: 'Sunsun',
      rating: 4.5,
      numReviews: 25,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Canister Sunsun HW-403A',
      category: 'Filtros',
      image: '/images/canister.jpg',
      price: 780,
      brand: 'Sunsun',
      rating: 5,
      numReviews: 32,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Ativador ADA',
      category: 'Substratos',
      image: '/images/ativadorAda.jpg',
      price: 320,
      brand: 'Ada',
      rating: 4.5,
      numReviews: 22,
      description: 'high quality product',
    },
  ],
};

export default data;